### ISSUE TITLE
'django_markdown' apare mentionat la app-uri de instalat in setari, dar in requirements lipseste.

### ISSUE THREAD

**Issue by AlexInntekt** [selfpower-ngo/selfpower.ro#14]
Am facut o instalare proaspata la mine din repo asta. Am instalat reqs intr-un env:

`pip3 install -r requirements/local.txt`

Si cand incerc sa fac un user din CLI:

`python3 src/manage.py createsuperuser`

Apare asta:
```
Debug is TRUE and : 
STATIC_ROOT:  /home/alex/repos/selfpower.ro/static 
MEDIA_ROOT:  /home/alex/repos/selfpower.ro/media
Traceback (most recent call last):
  File "src/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/alex/.local/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/alex/.local/lib/python3.6/site-packages/django/core/management/__init__.py", line 357, in execute
    django.setup()
  File "/home/alex/.local/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/alex/.local/lib/python3.6/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/home/alex/.local/lib/python3.6/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'django_markdown'
```

Daca caut `django_markdown` in proiect:

`grep -rnw 'django_markdown' .`

Vad asta:

```
./src/hub/admin.py:5:from django_markdown.admin import MarkdownModelAdmin
./src/hub/admin.py:6:from django_markdown.widgets import AdminMarkdownWidget
Binary file ./src/hub/__pycache__/admin.cpython-37.pyc matches
./src/hub/templates/proiecte_detail.html:2:{% load django_markdown %}
./src/blog/admin.py:4:from django_markdown.admin import MarkdownModelAdmin
./src/blog/admin.py:5:from django_markdown.widgets import AdminMarkdownWidget     # for Python 2.7
Binary file ./src/blog/__pycache__/models.cpython-37.pyc matches
Binary file ./src/blog/__pycache__/admin.cpython-37.pyc matches
./src/blog/templates/blog_post.html:2:{% load django_markdown %}
./src/blog/migrations/0001_initial.py:5:import django_markdown.models
./src/blog/migrations/0001_initial.py:20:                ('body', django_markdown.models.MarkdownField()),
Binary file ./src/blog/migrations/__pycache__/0001_initial.cpython-37.pyc matches
./src/blog/models.py:8:from django_markdown.models import MarkdownField  # to fix markdown
./src/templates/not_in_use/workshops_detail.html:2:{% load django_markdown %}

```

**Comment by ionescu77** [comment]
Ciudat.

django_markdown cred ca ramasese in urma, si a fost inlocuit cu django-markdown-app (care in settings.py ar trebui sa apara tot ca `django-markdown`.

Poate am pierdut ceva prin upgrade-uri?

Ma gandesc sa sterg si sa instalez din nou in repo.

La mine pip freeze in virtualenv python 3.7.7:

```bash
alabaster==0.7.12
astroid==2.4.2
Babel==2.8.0
certifi==2020.4.5.2
chardet==3.0.4
coverage==5.1
Django==2.2.13
django-debug-toolbar==2.2
django-markdown-app==0.9.6
django-nopassword==5.0.0
django-paypal==1.0.0
docopt==0.6.2
docutils==0.16
factory-boy==2.12.0
Faker==4.1.0
idna==2.9
imagesize==1.2.0
importlib-metadata==1.6.1
isort==4.3.21
Jinja2==2.11.2
lazy-object-proxy==1.5.0
mailchimp3==3.0.14
Markdown==3.2.2
MarkupSafe==1.1.1
mccabe==0.6.1
Online-W3C-Validator==0.3.11
packaging==20.4
pbr==5.4.5
Pillow==7.1.2
psycopg2-binary==2.8.5
Pygments==2.6.1
pylint==2.5.3
pylint-django==2.0.15
pylint-plugin-utils==0.6
pyparsing==2.4.7
python-dateutil==2.8.1
pytz==2020.1
requests==2.23.0
six==1.15.0
snowballstemmer==2.0.0
Sphinx==3.1.1
sphinxcontrib-applehelp==1.0.2
sphinxcontrib-devhelp==1.0.2
sphinxcontrib-htmlhelp==1.0.3
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.3
sphinxcontrib-serializinghtml==1.1.4
sqlparse==0.3.1
text-unidecode==1.3
toml==0.10.1
typed-ast==1.4.1
Unidecode==1.1.1
urllib3==1.25.9
wrapt==1.12.1
zipp==3.1.0
```

- si
```bash
python src/manage.py --version
Debug is TRUE and :
STATIC_ROOT:  /Users/razvansky/myProjects/selfpower/static
MEDIA_ROOT:  /Users/razvansky/myProjects/selfpower/media
2.2.13
```

**Comment by AlexInntekt** [comment]
Of, si daca instalez django_markdown e degeaba, ca e incompatibil cu dj 2.2
Un modul de migrare init__001 din appul blog importa django_markdown

Nu inteleg cum de la voi nu a fost problema asta

**Comment by ionescu77** [comment]
Sunt pe branch-ul develop.

Master este inca cu ce e pe live.

Am tot facut PR-uri de la dependabot, care a facut bump-up la package version in requirements. Poate nu am fost atent la ceva.

**Comment by ionescu77** [comment]
## @AlexInntekt 
- `activate` la final trebuie ENV variables.

- ce ai in `DJANGO_SETTINGS_MODULE`?
```bash
DJANGO_SETTINGS_MODULE=SelfpowerProject.settings.local
```

## Despre django-markdown -> django-markdown-app
`django-markdown-app==0.9.6`
https://pypi.org/project/django-markdown-app/

> Setup
> 
> .. note:: 'django_markdown' require 'django.contrib.staticfiles' in INSTALLED_APPS
> 
> - Add 'django_markdown' to INSTALLED_APPS ::
> 
> INSTALLED_APPS += ( 'django_markdown', )
> 
> 
> - Add django_markdown urls to base urls ::
> 
> path('markdown/', include( 'django_markdown.urls')),
> 
>

**Comment by AlexInntekt** [comment]
export DJANGO_SETTINGS_MODULE="SelfpowerProject.settings.local"

**Comment by AlexInntekt** [comment]
Pare sa fie rezolvat acum, problema era ca creasem mediul virtual cu python3.7 in loc de python 3.6

De curiozitate, voi ce versiuni folositi?

Multumesc tuturor

**Comment by ionescu77** [comment]
Me: 3.7.7

Parca dominic 3.8

Cred ca era de la DJANGO_SETTINGS_MODULE si eu uite de el si secret key cand mai dau jos cod si creez virtualenv :)
